.TH LIBVDEPLUG_VXVDEX 1 "September 04, 2016" "Virtual Distributed Ethernet"
.SH NAME
libvdeplug_vxvdex - vdeplug module for vde_switch based networks
.SH SYNOPSIS
libvdeplug_vxvdex.so
.SH DESCRIPTION
This is the libvdeplug module to join vxvde networks from private network namespaces.
libvdeplug_vxvdex needs the kernel module vxvdex.ko.

Vxvde is a distributed implementation of virtual networks. There is no need for extra processes
like virtual switches.

This module of libvdeplug4 can be used in any program supporting vde like
\fBvde_plug\fR, \fBkvm\fR, \fBqemu\fR, \fBuser-mode-linux\fR and \fBvirtualbox\fR.

The vde_plug_url syntax of this module is the following:
.RS
.br
\fBvxvdex://\fR[\fImulticast_addr\fR][\fB/\fIOPTION\fR][\fB/\fIOPTION\fR]
.RE

If \fImulticast_addr\fR is omitted libvdeplug_vxvdex uses the default addresses:
\fB239.a.b.c\fR for IPv4 and \fBff05:56de::xABC\fR for IPv6 (where a.b.c and ABC
are respectively the decimal and exadecimal representation of the group id of
the process using this module.
.SH OPTIONS
.TP
\fBv4\fR
use IPv4
.TP
\fBv6\fR
use IPv6
.TP
\fBport=\fR\fIPORT
define the multicast port (default value 14879)
.TP
\fBvni=\fR\fIVNI
define the virtual network identifier (default value 1).
(a group name can be used as VNI, in that case the vni is the group id).
.TP
\fBttl=\fR\fITTL
define the time-to-live (default value is the max ttl provided by the kernel module). 
.TP
\fBhashsize=\fR\fIHASHSIZE
set the size of the hash table for packet switching
.TP
\fBexpiretime=\fR\fIEXPIRETIME
set the maximum age in seconds of valid packet switching entries
.SH EXAMPLES
.B vxvdex://
.br
If the current user has effective gid=1000,
this vde_plug_url refers to the vxvdex network defined on the multicast address 239.0.3.232, vni=1000.
(3*256 + 232 = 1000).
.sp
Processes whose effective gid is 1000, using
.br
.B vxvdex:///v6/port=15000
.br
join the same vxvdex network defined by the multicast address ff05:56de::3e8, port 1500, vni is 1000.
(0x3e8 is 1000).

.SH NOTICE
Virtual Distributed Ethernet is not related in any way with
www.vde.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik"
i.e. the German "Association for Electrical, Electronic & Information
Technologies").
.SH SEE ALSO
\fBvde_plug\fP(1),
